In [3]:
import os
import glob
import pandas as pd

In [4]:
# Define working directory
os.chdir("C:/Users/samya/VS Code Projects/Python/Python Projects/Spotify_hit_predictor/backend")

In [5]:
ds00 = pd.read_csv('Original_data/dataset-of-00s.csv')
ds10 = pd.read_csv('Original_data/dataset-of-10s.csv')
ds60 = pd.read_csv('Original_data/dataset-of-60s.csv')
ds70 = pd.read_csv('Original_data/dataset-of-70s.csv')
ds80 = pd.read_csv('Original_data/dataset-of-80s.csv')
ds90 = pd.read_csv('Original_data/dataset-of-90s.csv')

In [6]:
# Combining all data into one dataframe
merge = [ds00, ds10, ds60, ds70, ds80, ds90]
df = pd.concat(merge)
df.reset_index(drop=True, inplace=True)
df

track             artist  \
0                               Lucky Man  Montgomery Gentry   
1                          On The Hotline       Pretty Ricky   
2                      Clouds Of Dementia         Candlemass   
3                Heavy Metal, Raise Hell!      Zwartketterij   
4                         I Got A Feelin'   Billy Currington   
...                                   ...                ...   
41101               (You're A) Go Nowhere       Reagan Youth   
41102                  La Fiebre de Norma       La Castañeda   
41103                          Good Times      Edie Brickell   
41104                               Inane              KMFDM   
41105  You Can Make History (Young Again)         Elton John   

                                        uri  danceability  energy  key  \
0      spotify:track:4GiXBCUF7H6YfNQsnBRIzl         0.578   0.471    4   
1      spotify:track:1zyqZONW985Cs4osz9wlsu         0.704   0.854   10   
2      spotify:track:6cHZf7RbxXCKwEkgAZT4mY         0.162   0.836    9   
3      spotify:track:2IjBPp2vMeX7LggzRN3iSX         0.188   0.994    4   
4      spotify:track:1tF370eYXUcWwkIvaq3IGz         0.630   0.764    2   
...                                     ...           ...     ...  ...   
41101  spotify:track:4e86fqSFhqRQk3Z9hm7XHt         0.396   0.795    9   
41102  spotify:track:43DFcnOZprnVlAFKwgBJ3e         0.621   0.655    9   
41103  spotify:track:6UPfnVoOq3y3BvapBIKs8J         0.562   0.314   10   
41104  spotify:track:2Ao3Wi4raEOQfKQiU9EU8y         0.622   0.781    7   
41105  spotify:track:3ca91BX2k7GSzEUsx1mPgI         0.664   0.739    2   

       loudness  mode  speechiness  acousticness  instrumentalness  liveness  \
0        -7.270     1       0.0289      0.368000          0.000000    0.1590   
1        -5.477     0       0.1830      0.018500          0.000000    0.1480   
2        -3.009     1       0.0473      0.000111          0.004570    0.1740   
3        -3.745     1       0.1660      0.000007          0.078400    0.1920   
4        -4.353     1       0.0275      0.363000          0.000000    0.1250   
...         ...   ...          ...           ...               ...       ...   
41101    -6.070     0       0.2340      0.000928          0.000209    0.1820   
41102    -6.281     0       0.0309      0.050600          0.006260    0.0937   
41103   -15.213     0       0.0298      0.440000          0.000011    0.1060   
41104    -6.080     1       0.0368      0.000101          0.755000    0.3830   
41105    -9.005     1       0.0262      0.106000          0.054200    0.3330   

       valence    tempo  duration_ms  time_signature  chorus_hit  sections  \
0        0.532  133.061       196707               4    30.88059        13   
1        0.688   92.988       242587               4    41.51106        10   
2        0.300   86.964       338893               4    65.32887        13   
3        0.333  148.440       255667               4    58.59528         9   
4        0.631  112.098       193760               4    22.62384        10   
...        ...      ...          ...             ...         ...       ...   
41101    0.762  152.943        82107               4    30.34109         6   
41102    0.690  134.167       211653               4    34.89506        10   
41103    0.571  166.847       189827               4    21.11763        10   
41104    0.214  120.051       330053               4    47.13558        11   
41105    0.458   92.257       293973               4    42.50341        14   

       target  
0           1  
1           1  
2           0  
3           0  
4           1  
...       ...  
41101       0  
41102       0  
41103       1  
41104       0  
41105       1  

[41106 rows x 19 columns]

In [7]:
df2 = df.drop(['track', 'artist', 'uri'], axis=1)

In [8]:
#Validation of correlation between variables
import numpy as np 
df3=df2.corr()

In [9]:
# Sin chorus_hit y speechiness
data = df2.values
X = df2[['danceability', 'energy', 'key', 'loudness','mode', 'acousticness', 'instrumentalness', 'liveness','valence', 'tempo', 'duration_ms', 'time_signature', 'sections']]  
y = data[:, 15]
print(data.shape, X.shape, y.shape)
data

(41106, 16) (41106, 13) (41106,)


array([[ 0.578  ,  0.471  ,  4.     , ..., 30.88059, 13.     ,  1.     ],
       [ 0.704  ,  0.854  , 10.     , ..., 41.51106, 10.     ,  1.     ],
       [ 0.162  ,  0.836  ,  9.     , ..., 65.32887, 13.     ,  0.     ],
       ...,
       [ 0.562  ,  0.314  , 10.     , ..., 21.11763, 10.     ,  1.     ],
       [ 0.622  ,  0.781  ,  7.     , ..., 47.13558, 11.     ,  0.     ],
       [ 0.664  ,  0.739  ,  2.     , ..., 42.50341, 14.     ,  1.     ]])

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=10)

## Data Preprocessing

In [11]:
#Scale features (X) using MinMaxScaler
from sklearn.preprocessing import MinMaxScaler
X_scaler = MinMaxScaler(feature_range=(0,1)).fit(X_train)

X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test) 

X_train_scaled

array([[0.78947368, 0.52283395, 0.81818182, ..., 0.05569473, 0.8       ,
        0.06508876],
       [0.54048583, 0.83094117, 0.81818182, ..., 0.03957652, 0.8       ,
        0.04142012],
       [0.5       , 0.66588373, 0.81818182, ..., 0.03176775, 0.8       ,
        0.03550296],
       ...,
       [0.57692308, 0.36777999, 0.81818182, ..., 0.09203629, 0.8       ,
        0.09467456],
       [0.41902834, 0.16070793, 0.63636364, ..., 0.0441886 , 0.8       ,
        0.04733728],
       [0.29554656, 0.24873856, 0.81818182, ..., 0.0506431 , 0.6       ,
        0.06508876]])

One-hot encode the labels

In [12]:
#One-hot encode output labels (y)
from tensorflow.keras.utils import to_categorical
y_train_categorical = to_categorical(y_train)
y_test_categorical = to_categorical(y_test)

y_train_categorical

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 1.],
       [1., 0.]], dtype=float32)

## Creating and defining our Deep Learning Model Architecture

In [13]:
#Create a sequential model
from tensorflow.keras.models import Sequential
model = Sequential() 

from tensorflow.keras.layers import Dense
number_inputs = 13  

#Create hidden layers
model.add(Dense(units=14,activation='relu', input_dim=number_inputs))
model.add(Dense(units=120,activation='relu'))
model.add(Dense(units=80,activation='relu'))


#Create output layer
number_classes = 2
model.add(Dense(units=number_classes, activation='softmax')) 

Number of Hidden Nodes 
https://stats.stackexchange.com/questions/181/how-to-choose-the-number-of-hidden-layers-and-nodes-in-a-feedforward-neural-netw#:~:text=The%20number%20of%20hidden%20neurons,size%20of%20the%20input%20layer.

In [14]:
#Model Summary
model.summary() 

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 14)                196       
                                                                 
 dense_1 (Dense)             (None, 120)               1800      
                                                                 
 dense_2 (Dense)             (None, 80)                9680      
                                                                 
 dense_3 (Dense)             (None, 2)                 162       
                                                                 
Total params: 11,838
Trainable params: 11,838
Non-trainable params: 0
_________________________________________________________________


In [15]:
#Compile the Model
import tensorflow as tf

opt = tf.keras.optimizers.Adam(learning_rate=0.001)
model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])

## Training the Model

In [16]:
#Training the Model
history = model.fit(X_train_scaled, y_train_categorical, epochs=500, batch_size=2000, shuffle=True, verbose=2)

Epoch 1/500
16/16 - 0s - loss: 0.6567 - accuracy: 0.6431 - 456ms/epoch - 28ms/step
Epoch 2/500
16/16 - 0s - loss: 0.5800 - accuracy: 0.7022 - 45ms/epoch - 3ms/step
Epoch 3/500
16/16 - 0s - loss: 0.5469 - accuracy: 0.7128 - 49ms/epoch - 3ms/step
Epoch 4/500
16/16 - 0s - loss: 0.5365 - accuracy: 0.7221 - 34ms/epoch - 2ms/step
Epoch 5/500
16/16 - 0s - loss: 0.5293 - accuracy: 0.7294 - 51ms/epoch - 3ms/step
Epoch 6/500
16/16 - 0s - loss: 0.5250 - accuracy: 0.7345 - 49ms/epoch - 3ms/step
Epoch 7/500
16/16 - 0s - loss: 0.5211 - accuracy: 0.7362 - 43ms/epoch - 3ms/step
Epoch 8/500
16/16 - 0s - loss: 0.5183 - accuracy: 0.7364 - 50ms/epoch - 3ms/step
Epoch 9/500
16/16 - 0s - loss: 0.5157 - accuracy: 0.7394 - 49ms/epoch - 3ms/step
Epoch 10/500
16/16 - 0s - loss: 0.5142 - accuracy: 0.7384 - 50ms/epoch - 3ms/step
Epoch 11/500
16/16 - 0s - loss: 0.5133 - accuracy: 0.7410 - 61ms/epoch - 4ms/step
Epoch 12/500
16/16 - 0s - loss: 0.5106 - accuracy: 0.7415 - 39ms/epoch - 2ms/step
Epoch 13/500
16/16 - 0s

Epoch 101/500
16/16 - 0s - loss: 0.4787 - accuracy: 0.7657 - 33ms/epoch - 2ms/step
Epoch 102/500
16/16 - 0s - loss: 0.4800 - accuracy: 0.7652 - 33ms/epoch - 2ms/step
Epoch 103/500
16/16 - 0s - loss: 0.4796 - accuracy: 0.7667 - 43ms/epoch - 3ms/step
Epoch 104/500
16/16 - 0s - loss: 0.4792 - accuracy: 0.7654 - 42ms/epoch - 3ms/step
Epoch 105/500
16/16 - 0s - loss: 0.4796 - accuracy: 0.7659 - 43ms/epoch - 3ms/step
Epoch 106/500
16/16 - 0s - loss: 0.4784 - accuracy: 0.7670 - 38ms/epoch - 2ms/step
Epoch 107/500
16/16 - 0s - loss: 0.4773 - accuracy: 0.7672 - 33ms/epoch - 2ms/step
Epoch 108/500
16/16 - 0s - loss: 0.4783 - accuracy: 0.7667 - 42ms/epoch - 3ms/step
Epoch 109/500
16/16 - 0s - loss: 0.4774 - accuracy: 0.7669 - 42ms/epoch - 3ms/step
Epoch 110/500
16/16 - 0s - loss: 0.4778 - accuracy: 0.7666 - 41ms/epoch - 3ms/step
Epoch 111/500
16/16 - 0s - loss: 0.4766 - accuracy: 0.7675 - 41ms/epoch - 3ms/step
Epoch 112/500
16/16 - 0s - loss: 0.4767 - accuracy: 0.7674 - 33ms/epoch - 2ms/step
Epoc

Epoch 200/500
16/16 - 0s - loss: 0.4623 - accuracy: 0.7763 - 56ms/epoch - 4ms/step
Epoch 201/500
16/16 - 0s - loss: 0.4640 - accuracy: 0.7768 - 34ms/epoch - 2ms/step
Epoch 202/500
16/16 - 0s - loss: 0.4618 - accuracy: 0.7774 - 42ms/epoch - 3ms/step
Epoch 203/500
16/16 - 0s - loss: 0.4615 - accuracy: 0.7786 - 43ms/epoch - 3ms/step
Epoch 204/500
16/16 - 0s - loss: 0.4630 - accuracy: 0.7761 - 44ms/epoch - 3ms/step
Epoch 205/500
16/16 - 0s - loss: 0.4620 - accuracy: 0.7771 - 37ms/epoch - 2ms/step
Epoch 206/500
16/16 - 0s - loss: 0.4619 - accuracy: 0.7783 - 42ms/epoch - 3ms/step
Epoch 207/500
16/16 - 0s - loss: 0.4620 - accuracy: 0.7781 - 42ms/epoch - 3ms/step
Epoch 208/500
16/16 - 0s - loss: 0.4616 - accuracy: 0.7781 - 34ms/epoch - 2ms/step
Epoch 209/500
16/16 - 0s - loss: 0.4616 - accuracy: 0.7785 - 41ms/epoch - 3ms/step
Epoch 210/500
16/16 - 0s - loss: 0.4628 - accuracy: 0.7766 - 42ms/epoch - 3ms/step
Epoch 211/500
16/16 - 0s - loss: 0.4620 - accuracy: 0.7769 - 41ms/epoch - 3ms/step
Epoc

Epoch 299/500
16/16 - 0s - loss: 0.4538 - accuracy: 0.7825 - 35ms/epoch - 2ms/step
Epoch 300/500
16/16 - 0s - loss: 0.4539 - accuracy: 0.7820 - 42ms/epoch - 3ms/step
Epoch 301/500
16/16 - 0s - loss: 0.4535 - accuracy: 0.7817 - 42ms/epoch - 3ms/step
Epoch 302/500
16/16 - 0s - loss: 0.4557 - accuracy: 0.7819 - 42ms/epoch - 3ms/step
Epoch 303/500
16/16 - 0s - loss: 0.4541 - accuracy: 0.7819 - 41ms/epoch - 3ms/step
Epoch 304/500
16/16 - 0s - loss: 0.4517 - accuracy: 0.7835 - 42ms/epoch - 3ms/step
Epoch 305/500
16/16 - 0s - loss: 0.4530 - accuracy: 0.7827 - 41ms/epoch - 3ms/step
Epoch 306/500
16/16 - 0s - loss: 0.4565 - accuracy: 0.7792 - 41ms/epoch - 3ms/step
Epoch 307/500
16/16 - 0s - loss: 0.4523 - accuracy: 0.7837 - 49ms/epoch - 3ms/step
Epoch 308/500
16/16 - 0s - loss: 0.4526 - accuracy: 0.7819 - 34ms/epoch - 2ms/step
Epoch 309/500
16/16 - 0s - loss: 0.4515 - accuracy: 0.7835 - 52ms/epoch - 3ms/step
Epoch 310/500
16/16 - 0s - loss: 0.4518 - accuracy: 0.7840 - 48ms/epoch - 3ms/step
Epoc

Epoch 398/500
16/16 - 0s - loss: 0.4452 - accuracy: 0.7855 - 50ms/epoch - 3ms/step
Epoch 399/500
16/16 - 0s - loss: 0.4459 - accuracy: 0.7860 - 52ms/epoch - 3ms/step
Epoch 400/500
16/16 - 0s - loss: 0.4478 - accuracy: 0.7853 - 41ms/epoch - 3ms/step
Epoch 401/500
16/16 - 0s - loss: 0.4453 - accuracy: 0.7865 - 49ms/epoch - 3ms/step
Epoch 402/500
16/16 - 0s - loss: 0.4460 - accuracy: 0.7859 - 43ms/epoch - 3ms/step
Epoch 403/500
16/16 - 0s - loss: 0.4458 - accuracy: 0.7846 - 50ms/epoch - 3ms/step
Epoch 404/500
16/16 - 0s - loss: 0.4471 - accuracy: 0.7857 - 50ms/epoch - 3ms/step
Epoch 405/500
16/16 - 0s - loss: 0.4447 - accuracy: 0.7884 - 42ms/epoch - 3ms/step
Epoch 406/500
16/16 - 0s - loss: 0.4442 - accuracy: 0.7866 - 50ms/epoch - 3ms/step
Epoch 407/500
16/16 - 0s - loss: 0.4467 - accuracy: 0.7857 - 50ms/epoch - 3ms/step
Epoch 408/500
16/16 - 0s - loss: 0.4461 - accuracy: 0.7855 - 50ms/epoch - 3ms/step
Epoch 409/500
16/16 - 0s - loss: 0.4452 - accuracy: 0.7856 - 51ms/epoch - 3ms/step
Epoc

Epoch 497/500
16/16 - 0s - loss: 0.4404 - accuracy: 0.7904 - 49ms/epoch - 3ms/step
Epoch 498/500
16/16 - 0s - loss: 0.4388 - accuracy: 0.7909 - 43ms/epoch - 3ms/step
Epoch 499/500
16/16 - 0s - loss: 0.4381 - accuracy: 0.7913 - 50ms/epoch - 3ms/step
Epoch 500/500
16/16 - 0s - loss: 0.4390 - accuracy: 0.7903 - 50ms/epoch - 3ms/step


## Validation of the Model

In [17]:
#Evaluate the Model using the testing data
#Compare Model performace between training and testing data
model_loss_train, model_accuracy_train = model.evaluate(X_train_scaled, y_train_categorical, verbose=2)
model_loss, model_accuracy = model.evaluate(X_test_scaled, y_test_categorical, verbose=2)

print(f"TRAINING DATA --> Loss: {model_loss_train}, Accuracy: {model_accuracy_train}")    
print(f"TESTING DATA --> Loss: {model_loss}, Accuracy: {model_accuracy}")

964/964 - 1s - loss: 0.4375 - accuracy: 0.7914 - 748ms/epoch - 775us/step
322/322 - 0s - loss: 0.4789 - accuracy: 0.7706 - 234ms/epoch - 726us/step
TRAINING DATA --> Loss: 0.43746301531791687, Accuracy: 0.7913652658462524
TESTING DATA --> Loss: 0.47885623574256897, Accuracy: 0.7705556154251099


## Saving the Trained Model

In [27]:
# Save the model
model.save("../Models/h5/schorus&speech.h5")